package com.kubocode.ParkingClubEscritura.util;

public enum Permission {
    READ_ALL_PRODUCTS,
    SAVE_ONE_PRODUCT,
    ADMIN_PERSONAl,
    USERS_PERSONAL,
    ALL_EMPRESAS,
    CREATE_SUCURSALES,
    SELECT_UPDATE_SUCURSALES,
    ALL_EMPLEADOS,
    READ_EMPLEADOS,
    UPDATE_TICKETS,
    READ_TICKETS,
    GET_PLAZAS,
    ALL_TARIFAS,
    GET_TARIFAS_MONTO,
    GET_NOMBRE_UBICACION_SUCURSAL;
}